#!/bin/sh
#
# Prepare for a new backup (just the changes)
#
####

# If there is no "current" directory, there should be nothing to do, as this
# will be the first backup for this distribution, and snapshot copies
# will be made from it.
#
[ -d current ] || exit

# Actually I have nothing to do at all!  I used to make a copy of the current
# before making the backup, but really even that is no longer needed!  All the
# various 'snapshot' cycles are now created AFTER the backup has been made.

# ---------------------------------
